name: Development Build (Galaxy A50)

on:
  workflow_dispatch:
  push:
    branches:
      - 'wip-*'

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        type: [aosp-12-e, aosp-12-p]

    steps:
      - uses: actions/checkout@v3

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Manila"
          timezoneMacos: "Asia/Manila"
          timezoneWindows: "Philippine Standard Time"

      - name: Export build branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: branch_name

      - name: Update Debian/Ubuntu Repositories
        run: sudo apt-get update

      - name: Install Debian/Ubuntu dependencies
        run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

      - name: Parse build arguments
        run: |
          echo "VARIANT=$(echo ${{ matrix.type }} | cut -d '-' -f1)" >> $GITHUB_ENV
          echo "ANDROID=$(echo ${{ matrix.type }} | cut -d '-' -f2)" >> $GITHUB_ENV
          echo "SELINUX=$(echo ${{ matrix.type }} | cut -d '-' -f3)" >> $GITHUB_ENV

      - name: Build Mint kernel (Magisk)
        run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --automated --device a50 --magisk --variant $VARIANT --android $ANDROID -$SELINUX

      - name: Upload kernel image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }} Kernel Image (Magisk)
          path: 'tools/make/boot.img'
          if-no-files-found: error

      - name: Build Mint kernel (No-Root)
        run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --automated --device a50 --variant $VARIANT --android $ANDROID -$SELINUX

      - name: Upload kernel image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }} Kernel Image (No-Root)
          path: 'tools/make/boot.img'
          if-no-files-found: error

      - name: Prepare release package
        run: |
          mkdir -p ./release
          mv -f `find ./ -iname "MintBeta-*.zip"` ./release/

      - name: Prepare build config artifact
        run: cp .config ./release/kernel_config_a50_$VARIANT-$ANDROID-$SELINUX.txt

      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }} Release
          path: 'release'
          if-no-files-found: error

      - name: Upload build config artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }} Kernel Configs
          path: release/kernel_config_a50_${{ env.VARIANT }}-${{ env.ANDROID }}-${{ env.SELINUX }}.txt
          if-no-files-found: error

  release:
    name: Release files and configs
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Merge releases
      run: |
        set -eo pipefail
        gh run download -p "*Release" --dir ./release
        find ./release -mindepth 2 -type f -exec mv {} ./release \;

    - name: Delete build configs and release directories
      run: |
        set -eo pipefail
        rm -f ./release/kernel_config_*.txt
        rm -rf ./release/aosp-* ./release/oneui-*

    - name: Delete older release
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 12
        delete_tag_pattern: "xbeta"
        
    - name: Upload release
      uses: Hs1r1us/Release-AIO@v1.0
      with:
        tag_name: xbeta-${{ github.run_number }}_a50dx
        prerelease: true
        release_name: Galaxy A50 (beta-${{ github.run_number }})
        body_path: "./tools/make/release/a50-development.md"
        asset_files: './release'
