name: Stable Release Build (Galaxy A50)

on:
  push:
    branches:
      - 'android-*'

jobs:
  aosp-s-m:
    name: Build AOSP 12 (Magisk)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --magisk --automated --device a50 --variant aosp --android 12

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname Mint-*.zip` ./release/

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50_aosp-s-m.txt

    - name: Upload build config artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kernel Configs
        path: 'release/kernel_config_a50_aosp-s-m.txt'
        if-no-files-found: error

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: 'release'
        if-no-files-found: error

  release:
    name: Release files and configs
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    needs: [aosp-s-m]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Merge Releases
      uses: actions/download-artifact@v2
      with: 
        name: Release
        path: release

    - name: Delete build config files
      run: |
          set -eo pipefail
          rm -rf ./release/kernel_config_*.txt

    - name: Upload release
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag
        tag_name: mainline-${{ github.run_number }}_a50dx
        prerelease: true
        release_name: Mint Stable
        body_path: "./tools/make/release/a50-release.md"
        asset_files: './release'
